apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-argocd
  labels:
    app: demo-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-argocd
  template:
    metadata:
      labels:
        app: demo-argocd
    spec:
      containers:
      - name: web
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: html-content
        configMap:
          name: demo-argocd-html