apiVersion: v1
kind: Service
metadata:
  name: demo-argocd-service
  labels:
    app: demo-argocd
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: demo-argocd