apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: django-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/robertolandry/argocd
    argocd-image-updater.argoproj.io/argocd.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/ngueagho/ci-cd_build_django.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
